swagger: "2.0"
info:
  version: "1.0.0"
  title: "Riby Support Authentication Service"
  description: "This is the authentication service of riby support system."
  termsOfService: "https://riby.ng/" 
  contact:
    email: "riby@gmail.com"
  license:
    name: "Apache 2.0"
    url: "http://www.apache.org/licenses/LICENSE-2.0.html"
  servers:
    - url: "http://localhost:8080"
      description: "Development server"
    - url: "http://localhost:8080"
      description: "Production server"

schemes: ["http", "https"]

paths:

  #QA Login
  /api/v1/qa/login:
    post:
      summary: "QA Login"
      description: "QA Login to the system"
      operationId: "login"
      consumes:
        - "application/json"
      produces:
        - "application/json"
      parameters:
        - in: "body"
          name: "body"
          description: "Login to the system"
          required: true
      responses:
        200:
          description: "successful operation"
          message: "Login successful"
        400:
          description: "Invalid username/password supplied"
        404:
          description: "User not found"
  /api/v1/qa/register:
    post:
      summary: "QA Register"
      description: "QA Register to the system"
      operationId: "register"
      consumes:
        - "application/json"
      produces:
        - "application/json"
      parameters:
        - in: "body"
          name: "body"
          description: "Register to the system"
          required: true
      responses:
        200:
          description: "successful operation"
          message: "Registration successful"
        400:
          description: "Invalid username/password supplied"
        404:
          description: "User not found"